export enum ENV_CONSTANTS {
  APP_PORT = 'APP_PORT',
  NODE_ENV = 'NODE_ENV',
  API_VERSION = 'API_VERSION',
  ENABLE_DOCUMENTATION = 'ENABLE_DOCUMENTATION',
  API_PREFIX = 'API_PREFIX',
  DB_HOST = 'DB_HOST',
  DB_PORT = 'DB_PORT',
  DB_USERNAME = 'DB_USERNAME',
  DB_PASSWORD = 'DB_PASSWORD',
  DB_DATABASE = 'DB_DATABASE',
  ENABLE_ORM_LOGS = 'ENABLE_ORM_LOGS',
  MAX_CONNECTIONS = 'MAX_CONNECTIONS',
  DB_SSL_ENABLED = 'DB_SSL_ENABLED',
  DB_REJECT_UNAUTHORIZED = 'DB_REJECT_UNAUTHORIZED',
  DB_CA = 'DB_CA',
  DB_KEY = 'DB_KEY',
  DB_CERT = 'DB_CERT',
}

export const ENV_CONSTANTS_VALUES = {
  PRODUCTION: 'production',
  DEVELOPMENT: 'development',
  TEST: 'test',
  LOCAL: 'local',
};
